import type { WorkerJobRole, CustomerType, WageType, ShiftType, SkillLevel } from "@prisma/client";
import type { WorkerCategoryCode } from "../src/lib/worker-categories";

export type SeedWorker = {
  name: string;
  nameUrdu: string;
  fatherName: string;
  cnic: string;
  phone: string;
  address: string;
  categoryCode?: WorkerCategoryCode;
  jobRole: WorkerJobRole;
  workDescription: string;
  department: string;
  dailyWage: number;
  perBrickRate: number;
  monthlySalary?: number;
  perTruckRate?: number;
  wageType?: WageType;
  shiftType?: ShiftType;
  skillLevel?: SkillLevel;
  standardHoursPerDay: number;
  shiftStart: string;
  bricksTargetPerDay?: number;
  dailyTarget?: number;
  productionAssignment?: string;
  advanceBalance?: number;
};

export type SeedCustomer = {
  name: string;
  phone: string;
  companyName?: string;
  customerType: CustomerType;
  contactPerson?: string;
  email?: string;
  address: string;
  city: string;
  notes?: string;
  balance?: number;
};

export const SEED_WORKERS: SeedWorker[] = [
  {
    name: "Muhammad Aslam",
    nameUrdu: "محمد اسلم",
    fatherName: "Allah Ditta",
    cnic: "35202-1111111-1",
    phone: "+923001111001",
    address: "Chak 12, Sheikhupura",
    jobRole: "MOLDING",
    workDescription: "Hand molding — 900 bricks/day target",
    department: "Molding",
    dailyWage: 1800,
    perBrickRate: 0.18,
    standardHoursPerDay: 8,
    shiftStart: "06:00",
    bricksTargetPerDay: 900,
  },
  {
    name: "Rasheed Ahmed",
    nameUrdu: "رشید احمد",
    fatherName: "Ghulam Muhammad",
    cnic: "35202-1111112-2",
    phone: "+923001111002",
    address: "Village Kot Abdul Malik, Sheikhupura",
    jobRole: "MOLDING",
    workDescription: "Molding machine operator",
    department: "Molding",
    dailyWage: 2000,
    perBrickRate: 0.2,
    standardHoursPerDay: 9,
    shiftStart: "05:30",
    bricksTargetPerDay: 1100,
  },
  {
    name: "Imran Khan",
    nameUrdu: "عمران خان",
    fatherName: "Bashir Ahmed",
    cnic: "35202-1111113-3",
    phone: "+923001111003",
    address: "Ferozewala, Sheikhupura",
    jobRole: "KILN_OPERATOR",
    workDescription: "Kiln firing — night shift lead",
    department: "Kiln",
    dailyWage: 2200,
    perBrickRate: 0.05,
    standardHoursPerDay: 10,
    shiftStart: "20:00",
  },
  {
    name: "Allah Ditta",
    nameUrdu: "اللہ دitta",
    fatherName: "Maula Bakhsh",
    cnic: "35202-1111114-4",
    phone: "+923001111004",
    address: "Bhatha Road, Muridke",
    jobRole: "KILN_OPERATOR",
    workDescription: "Temperature monitoring & coal feed",
    department: "Kiln",
    dailyWage: 2100,
    perBrickRate: 0.05,
    standardHoursPerDay: 9,
    shiftStart: "06:00",
  },
  {
    name: "Bashir Ali",
    nameUrdu: "بشیر علی",
    fatherName: "Khuda Bakhsh",
    cnic: "35202-1111115-5",
    phone: "+923001111005",
    address: "Narang Mandi, Sheikhupura",
    jobRole: "LOADER",
    workDescription: "Truck & kiln loading",
    department: "Yard",
    dailyWage: 1700,
    perBrickRate: 0.08,
    standardHoursPerDay: 8,
    shiftStart: "07:00",
  },
  {
    name: "Tariq Mehmood",
    nameUrdu: "طارق محمود",
    fatherName: "Ashraf",
    cnic: "35202-1111116-6",
    phone: "+923001111006",
    address: "Safdarabad, Sheikhupura",
    jobRole: "UNLOADER",
    workDescription: "Unloading cooked bricks to yard",
    department: "Yard",
    dailyWage: 1650,
    perBrickRate: 0.08,
    standardHoursPerDay: 8,
    shiftStart: "07:30",
  },
  {
    name: "Nadeem Hussain",
    nameUrdu: "ندیم حسین",
    fatherName: "Ramzan",
    cnic: "35202-1111117-7",
    phone: "+923001111007",
    address: "Sharaqpur, Sheikhupura",
    jobRole: "QUALITY_CHECK",
    workDescription: "Grade A/B sorting & wastage log",
    department: "Quality",
    dailyWage: 1900,
    perBrickRate: 0.12,
    standardHoursPerDay: 8,
    shiftStart: "08:00",
    bricksTargetPerDay: 5000,
  },
  {
    name: "Khalid Mehmood",
    nameUrdu: "خالد محمود",
    fatherName: "Sadiq",
    cnic: "35202-1111118-8",
    phone: "+923001111008",
    address: "Lahore Road, Gujranwala",
    jobRole: "DISPATCH",
    workDescription: "Dispatch challan & truck coordination",
    department: "Dispatch",
    dailyWage: 2000,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "09:00",
  },
  {
    name: "Shabbir Ahmad",
    nameUrdu: "شبیر احمد",
    fatherName: "Latif",
    cnic: "35202-1111119-9",
    phone: "+923001111009",
    address: "GT Road, Lahore",
    jobRole: "MAINTENANCE",
    workDescription: "Kiln & machine repair",
    department: "Maintenance",
    dailyWage: 2500,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "08:00",
  },
  {
    name: "Zafar Iqbal",
    nameUrdu: "ظفر اقبال",
    fatherName: "Akbar",
    cnic: "35202-1111120-0",
    phone: "+923001111010",
    address: "Bhatha gate, Sheikhupura",
    jobRole: "SECURITY",
    workDescription: "Gate security & visitor log",
    department: "Gate",
    dailyWage: 1500,
    perBrickRate: 0,
    standardHoursPerDay: 12,
    shiftStart: "06:00",
  },
  {
    name: "Farhan Ali",
    nameUrdu: "فرحان علی",
    fatherName: "Nawaz",
    cnic: "35202-1111121-1",
    phone: "+923001111011",
    address: "Office quarter, bhatha",
    jobRole: "OFFICE",
    workDescription: "Files, petty cash & store register",
    department: "Office",
    dailyWage: 1800,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "09:00",
  },
  {
    name: "Waseem Akram",
    nameUrdu: "وسیم اکرم",
    fatherName: "Anwar",
    cnic: "35202-1111122-2",
    phone: "+923001111012",
    address: "Chak 45, Sheikhupura",
    jobRole: "MOLDING",
    workDescription: "Clay mixing & mold preparation",
    department: "Molding",
    dailyWage: 1750,
    perBrickRate: 0.16,
    standardHoursPerDay: 8,
    shiftStart: "06:00",
    bricksTargetPerDay: 800,
    advanceBalance: 8000,
  },
  {
    name: "Javed Iqbal",
    nameUrdu: "جاوید اقبال",
    fatherName: "Hussain",
    cnic: "35202-1111123-3",
    phone: "+923001111013",
    address: "Muridke bypass",
    jobRole: "LOADER",
    workDescription: "Forklift & hand cart loading",
    department: "Yard",
    dailyWage: 1680,
    perBrickRate: 0.09,
    standardHoursPerDay: 9,
    shiftStart: "06:30",
  },
  {
    name: "Sajid Mahmood",
    nameUrdu: "ساجد محمود",
    fatherName: "Rafique",
    cnic: "35202-1111124-4",
    phone: "+923001111014",
    address: "Hafizabad road",
    jobRole: "KILN_OPERATOR",
    workDescription: "Assistant kiln — day shift",
    department: "Kiln",
    dailyWage: 1950,
    perBrickRate: 0.05,
    standardHoursPerDay: 8,
    shiftStart: "06:00",
  },
  {
    name: "Amjad Ali",
    nameUrdu: "امجد علی",
    fatherName: "Yousaf",
    cnic: "35202-1111125-5",
    phone: "+923001111015",
    address: "Sangla Hill",
    jobRole: "QUALITY_CHECK",
    workDescription: "Broken brick count & reports",
    department: "Quality",
    dailyWage: 1850,
    perBrickRate: 0.1,
    standardHoursPerDay: 8,
    shiftStart: "08:00",
  },
  {
    name: "Hafeez Ullah",
    nameUrdu: "حفیظ اللہ",
    fatherName: "Karim",
    cnic: "35202-1111126-6",
    phone: "+923001111016",
    address: "Mananwala",
    jobRole: "MOLDING",
    workDescription: "Sun-drying & stacking raw bricks",
    department: "Molding",
    dailyWage: 1600,
    perBrickRate: 0.14,
    standardHoursPerDay: 8,
    shiftStart: "06:00",
    bricksTargetPerDay: 750,
  },
  {
    name: "Rizwan Haider",
    nameUrdu: "رضوان حیدر",
    fatherName: "Haider",
    cnic: "35202-1111127-7",
    phone: "+923001111017",
    address: "Kala Shah Kaku",
    jobRole: "DISPATCH",
    workDescription: "Weighbridge & delivery slips",
    department: "Dispatch",
    dailyWage: 1900,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "08:30",
  },
  {
    name: "Nasir Abbas",
    nameUrdu: "ناصر عباس",
    fatherName: "Abbas",
    cnic: "35202-1111128-8",
    phone: "+923001111018",
    address: "Bhatha colony",
    jobRole: "MAINTENANCE",
    workDescription: "Diesel pump & generator",
    department: "Maintenance",
    dailyWage: 2300,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "07:00",
  },
  {
    name: "Yasir Mahmood",
    nameUrdu: "یاسر محمود",
    fatherName: "Mahmood",
    cnic: "35202-1111129-9",
    phone: "+923001111019",
    address: "Faisalabad road",
    jobRole: "UNLOADER",
    workDescription: "Night unloading crew",
    department: "Yard",
    dailyWage: 1700,
    perBrickRate: 0.08,
    standardHoursPerDay: 10,
    shiftStart: "22:00",
  },
  {
    name: "Faisal Raza",
    nameUrdu: "فیصل رضا",
    fatherName: "Raza",
    cnic: "35202-1111130-0",
    phone: "+923001111020",
    address: "Gujrat district",
    jobRole: "OTHER",
    categoryCode: "GENERAL_HELPER",
    workDescription: "General labour — multi department",
    department: "General",
    dailyWage: 1500,
    perBrickRate: 0.1,
    standardHoursPerDay: 8,
    shiftStart: "07:00",
  },
  {
    name: "Ghulam Rasool",
    nameUrdu: "غلام رسول",
    fatherName: "Mitha",
    cnic: "35202-1111131-1",
    phone: "+923001111021",
    address: "Clay pit, bhatha",
    jobRole: "OTHER",
    categoryCode: "CLAY_MITTI",
    workDescription: "Clay mixing & mitti supply",
    department: "Production",
    dailyWage: 1600,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "06:00",
  },
  {
    name: "Arshad Mahmood",
    nameUrdu: "ارشد محمود",
    fatherName: "Mahmood",
    cnic: "35202-1111132-2",
    phone: "+923001111022",
    address: "Yard, Sheikhupura",
    jobRole: "OTHER",
    categoryCode: "TRACTOR_DRIVER",
    workDescription: "Tractor — raw brick yard moves",
    department: "Transport",
    dailyWage: 0,
    monthlySalary: 36000,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "07:00",
  },
  {
    name: "Nawaz Truck Wala",
    nameUrdu: "نواز ٹرک والا",
    fatherName: "Sultan",
    cnic: "35202-1111133-3",
    phone: "+923001111023",
    address: "GT Road depot",
    jobRole: "DISPATCH",
    categoryCode: "TRUCK_DRIVER",
    workDescription: "Customer delivery truck",
    department: "Transport",
    dailyWage: 0,
    monthlySalary: 43000,
    perBrickRate: 0,
    standardHoursPerDay: 10,
    shiftStart: "08:00",
  },
  {
    name: "Shaukat Wood",
    nameUrdu: "شوکت لکڑی",
    fatherName: "Hidayat",
    cnic: "35202-1111139-9",
    phone: "+923001111029",
    address: "Wood stack, bhatha",
    jobRole: "OTHER",
    categoryCode: "WOOD_FUEL",
    workDescription: "Firewood & wood waste to kiln — day shift",
    department: "Kiln",
    dailyWage: 1850,
    perBrickRate: 0,
    standardHoursPerDay: 9,
    shiftStart: "05:00",
  },
  {
    name: "Dilawar Khan",
    nameUrdu: "دلاور خان",
    fatherName: "Khan",
    cnic: "35202-1111134-4",
    phone: "+923001111024",
    address: "Coal yard",
    jobRole: "OTHER",
    categoryCode: "FUEL_COAL",
    workDescription: "Coal feeding where required",
    department: "Kiln",
    dailyWage: 1750,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "06:00",
  },
  {
    name: "Iqbal Pump",
    nameUrdu: "اقبال پمپ",
    fatherName: "Hussain",
    cnic: "35202-1111135-5",
    phone: "+923001111025",
    address: "Water tank, bhatha",
    jobRole: "OTHER",
    categoryCode: "WATER_PUMP",
    workDescription: "Diesel water pump operator",
    department: "Utilities",
    dailyWage: 1650,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "05:30",
  },
  {
    name: "Malik Rafique",
    nameUrdu: "ملک رفیق",
    fatherName: "Muhammad",
    cnic: "35202-1111136-6",
    phone: "+923001111026",
    address: "Site office",
    jobRole: "OFFICE",
    categoryCode: "SUPERVISOR",
    workDescription: "Production supervisor — all shifts",
    department: "Administration",
    dailyWage: 0,
    monthlySalary: 58000,
    perBrickRate: 0,
    standardHoursPerDay: 9,
    shiftStart: "06:00",
    skillLevel: "FOREMAN",
  },
  {
    name: "Saleem Electrician",
    nameUrdu: "سلیم الیکٹریشن",
    fatherName: "Akhtar",
    cnic: "35202-1111137-7",
    phone: "+923001111027",
    address: "Workshop",
    jobRole: "MAINTENANCE",
    categoryCode: "ELECTRICIAN",
    workDescription: "Motors, wiring, kiln electrics",
    department: "Maintenance",
    dailyWage: 2100,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "08:00",
  },
  {
    name: "Rukhsana Bibi",
    nameUrdu: "رخسانہ بی بی",
    fatherName: "Ali",
    cnic: "35202-1111138-8",
    phone: "+923001111028",
    address: "Staff quarters",
    jobRole: "OTHER",
    categoryCode: "CLEANING_STAFF",
    workDescription: "Office & site cleaning",
    department: "Administration",
    dailyWage: 1400,
    perBrickRate: 0,
    standardHoursPerDay: 8,
    shiftStart: "07:00",
  },
];

export const SEED_CUSTOMERS: SeedCustomer[] = [
  {
    name: "Al-Rehman Builders",
    phone: "+924211122201",
    companyName: "Al-Rehman Construction Pvt Ltd",
    customerType: "BUILDER",
    contactPerson: "Ch. Usman",
    email: "usman@alrehmanbuilders.pk",
    address: "DHA Phase 5, Lahore",
    city: "Lahore",
    notes: "Monthly bulk orders — Grade A preferred",
    balance: 450000,
  },
  {
    name: "Skyline Housing Scheme",
    phone: "+924211122202",
    companyName: "Skyline Developers",
    customerType: "BUILDER",
    contactPerson: "Eng. Sara Malik",
    address: "Canal Road, Faisalabad",
    city: "Faisalabad",
    balance: 280000,
  },
  {
    name: "Rana Contractors",
    phone: "+924211122203",
    companyName: "Rana & Sons",
    customerType: "CONTRACTOR",
    contactPerson: "Rana Nadeem",
    address: "GT Road, Gujranwala",
    city: "Gujranwala",
    notes: "Government school project — challan required",
    balance: 120000,
  },
  {
    name: "Metro Brick Mart",
    phone: "+924211122204",
    companyName: "Metro Retail",
    customerType: "RETAILER",
    contactPerson: "Haji Irfan",
    address: "Main Bazaar, Sheikhupura",
    city: "Sheikhupura",
    balance: 35000,
  },
  {
    name: "Punjab Wholesale Bricks",
    phone: "+924211122205",
    companyName: "PWB Traders",
    customerType: "WHOLESALER",
    contactPerson: "Malik Javed",
    address: "Industrial Area, Lahore",
    city: "Lahore",
    notes: "Pickup from yard — cash on dispatch",
    balance: 0,
  },
  {
    name: "PWD Sheikhupura",
    phone: "+924211122206",
    companyName: "Public Works Department",
    customerType: "GOVERNMENT",
    contactPerson: "Sub-Engineer Kamran",
    address: "Civil Secretariat link road",
    city: "Sheikhupura",
    balance: 890000,
  },
  {
    name: "Green Valley Homes",
    phone: "+924211122207",
    companyName: "Green Valley Pvt Ltd",
    customerType: "BUILDER",
    contactPerson: "Ahmad Raza",
    address: "Muridke interchange",
    city: "Sheikhupura",
    balance: 175000,
  },
  {
    name: "Quick Build Supplies",
    phone: "+924211122208",
    customerType: "RETAILER",
    contactPerson: "Bilal Hussain",
    address: "Sargodha Road, Lahore",
    city: "Lahore",
    balance: 22000,
  },
  {
    name: "National Highway Contractor",
    phone: "+924211122209",
    companyName: "NHC Ltd",
    customerType: "CONTRACTOR",
    contactPerson: "Col. (Retd) Hamid",
    address: "N-5 Highway depot",
    city: "Lahore",
    balance: 560000,
  },
  {
    name: "Family Plot — Hassan",
    phone: "+923331112210",
    customerType: "OTHER",
    contactPerson: "Hassan Ali",
    address: "Village Kot, Sheikhupura",
    city: "Sheikhupura",
    notes: "Small home construction — 5000 bricks",
    balance: 15000,
  },
];
